name: mi_card
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.3
  social_media_buttons: ^1.0.0
  flutter_social_button: ^1.1.4+1
  flutter_vector_icons: ^1.0.0
  url_launcher: ^6.1.12
cupertino_icons: ^0.1.2
google_fonts: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/portretCV.png
  fonts:
  - family: Pacifico
    fonts:
      - asset: fonts/Pacifico-Regular.ttf
  
  - family: Roboto
    fonts:
      - asset: fonts/Roboto-Light.ttf
        
